[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"

[lib]
name = "utils"
path = "src/lib/rs/lib.rs"

[[bin]]
name = "day02"
path = "src/main/rs/day02.rs"
